### ISSUE TITLE
要望

### ISSUE THREAD

**Issue by miyaga** [avaQuickBoot/avaQuickBoot#1]
すごく使いやすくていいツールだと思います。
ただ、ゲーム起動をダブルクリックのみではなく、アカウント選択状態で「ゲーム起動」のようなボタンをクリックするだけで起動できるようになると僅かにかもしれませんがより快適になるかと思います。

**Comment by avaQuickBoot** [comment]
miyaga様

要望ありがとうございます。
「AVA実行」ボタンを配置したVersion 1.1.3を公開いたしました。

ほかにも要望があればほどほどによろしくお願いします。
